{
 "title": "CloudSQL",
 "description": "Visualize GCP CloudSQL metrics",
 "tags": [
  "gcpexporter",
  "sql"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dimension_database_id",
    "label": "dimension_database_id",
    "query": {
     "query": "label_values(cloudsql_googleapis_com_database_cpu_utilization{exported_job=\"cloudsql\"}, dimension_database_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": {
      "dimension_database_id": "$dimension_database_id"
     },
     "expr": "cloudsql_googleapis_com_database_cpu_utilization * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_database_id}}",
     "metricName": "CPUUtilization",
     "namespace": "GCP/SQL",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections (max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": {
      "dimension_database_id": "$dimension_database_id"
     },
     "expr": "cloudsql_googleapis_com_database_postgresql_num_backends",
     "expression": " ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_database_id}}",
     "metricName": "DatabaseConnections",
     "namespace": "GCP/SQL",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Memory Usage (min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": {
      "dimension_database_id": "$dimension_database_id"
     },
     "expr": "cloudsql_googleapis_com_database_memory_utilization * 100",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_database_id}}",
     "metricName": "MemoryUsage",
     "namespace": "GCP/SQL",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Utilization (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": {
      "dimension_database_id": "$dimension_database_id"
     },
     "expr": "cloudsql_googleapis_com_database_disk_utilization * 100",
     "expression": "cloudsql_googleapis_com_database_disk_utilization",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dimension_database_id}}",
     "metricName": "ReadIOPS",
     "namespace": "GCP/SQL",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}