{
 "title": "Redis",
 "description": "Visualize Redis GCP metrics",
 "tags": [
  "redis",
  "gcp",
  "gcpexporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dimension_cluster_id",
    "label": "Redis Instance",
    "query": {
     "query": "label_values(redis_googleapis_com_clients_connected, dimension_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "redis_googleapis_com_cluster_cpu_maximum_utilization * 100",
     "legendFormat": "{{dimension_cluster_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "redis_googleapis_com_cluster_memory_maximum_utilization * 100",
     "legendFormat": "{{dimension_cluster_id}}"
    }
   ]
  },
  {
   "title": "Client Connections (count)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "redis_googleapis_com_cluster_clients_maximum_connected_clients",
     "legendFormat": "{{dimension_cluster_id}}"
    }
   ]
  }
 ]
}