{
 "title": "Worker Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scavengers running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without (instance, pod) (started)) - (sum without (instance, pod) (stopped or started*0))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Completed scan tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_done[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Dropped tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_dropped[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_err[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Deferred tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_deferred[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Executions scavenger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Validation Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_validation_requests[10m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "DetailedErrors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_validation_failures[5m]))",
     "legendFormat": "{{failure}}"
    }
   ]
  },
  {
   "title": "ExecutionsLeftToScan",
   "type": "graph",
   "description": "Might stuck until scavenger rerun in case of worker crash.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod)(executions_outstanding)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "TaskQueue scavenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outstanding scavenger tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_outstanding)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Processed taskqueue tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_processed)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Deleted taskqueue tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_deleted)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Processed tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(task_processed)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Deleted tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(task_deleted)",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  { "title": "History scavenger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_success[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Skips",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_skips[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(scavenger_errors[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Search attributes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Add search attributes failure count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum without (instance, pod) (rate(add_search_attributes_failures[1m]))"
      }
     ]
    }
   ]
  },
  { "title": "Batcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(batcher_processor_requests[1m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(batcher_processor_errors[1m]))"
    }
   ]
  },
  { "title": "Parent close policy processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(parent_close_policy_processor_requests[1m]))",
     "legendFormat": "{{operation}}-{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(parent_close_policy_processor_errors[5m]))",
     "legendFormat": "{{operation}}-{{temporal_namespace}}"
    }
   ]
  },
  { "title": "Replicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Dlq Enqueue Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(namespace_replication_dlq_enqueue_requests[1m]))",
     "legendFormat": "{{operation}}-{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "DLQ enqueue fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(replicator_dlq_enqueue_fails[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(replicator_messages[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Messages Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(replicator_messages_dropped[1m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum without (instance, pod)(rate(replicator_dlq_enqueue_fails[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum without (instance, pod)(rate(replicator_errors[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}