{
 "title": " Flyte Propeller Dashboard",
 "description": "Flyte Propeller Dashboard. This is great for monitoring FlytePropeller / Flyte data plane deployments. This is mostly useful for the Flyte deployment maintainer",
 "tags": [
  "flyte",
  "prometheus",
  "flytepropeller",
  "flyte-dataplane"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Core metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free workers count",
   "type": "timeseries",
   "description": "The number of golang goroutines available to accept new work from the main workqueue. Each worker can process one item from the workqueue at a time.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:free_workers_count) by (kubernetes_pod_name)",
     "query": "sum(flyte:propeller:all:free_workers_count) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Round success/error rate",
   "type": "timeseries",
   "description": "Round success, error and total rates. Also includes total rate including streaks within a single round. The streak rate graph should match the difference between the totals with and without streaks.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flyte:propeller:all:round:success_count[5m]))",
     "legendFormat": "success",
     "query": "sum(rate(flyte:propeller:all:round:success_count[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:error_count[5m]))",
     "legendFormat": "error",
     "query": "sum(rate(flyte:propeller:all:round:error_count[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:round_total_ms_count[5m]))",
     "legendFormat": "total",
     "query": "sum(rate(flyte:propeller:all:round:round_total_ms_count[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:round_time_unlabeled_ms_count[5m]))",
     "legendFormat": "total-including-streaks",
     "query": "sum(rate(flyte:propeller:all:round:round_time_unlabeled_ms_count[5m]))"
    }
   ]
  },
  {
   "title": "Error rate breakdown",
   "type": "timeseries",
   "description": "Error rates for each type of failure that may occur as propeller is traversing the workflow DAG.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flyte:propeller:all:round:system_error_unlabeled[5m]))",
     "legendFormat": "system",
     "query": "sum(rate(flyte:propeller:all:round:system_error_unlabeled[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:abort_error_unlabeled[5m]))",
     "legendFormat": "abort",
     "query": "sum(rate(flyte:propeller:all:round:abort_error_unlabeled[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:panic_unlabeled[5m]))",
     "legendFormat": "panic",
     "query": "sum(rate(flyte:propeller:all:round:panic_unlabeled[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:not_found[5m]))",
     "legendFormat": "not-found",
     "query": "sum(rate(flyte:propeller:all:round:not_found[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:round:skipped[5m]))",
     "legendFormat": "skipped",
     "query": "sum(rate(flyte:propeller:all:round:skipped[5m]))"
    }
   ]
  },
  {
   "title": "Streak rate",
   "type": "timeseries",
   "description": "Streaks are when propeller iterates over the same workflow multiple times in a single round. This is an optimisation technique.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flyte:propeller:all:round:streak_length_unlabeled[5m]))",
     "query": "sum(rate(flyte:propeller:all:round:streak_length_unlabeled[5m]))"
    }
   ]
  },
  {
   "title": "Plugin Success/Failure rate",
   "type": "timeseries",
   "description": "Success vs failure rate for the various plugins used for each node e.g. k8s plugin or spark plugin.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"flyte:propeller:all:plugin:.*_success_unlabeled\"}[5m]))",
     "legendFormat": "success",
     "query": "sum(rate({__name__=~\"flyte:propeller:all:plugin:.*_success_unlabeled\"}[5m]))"
    },
    {
     "expr": "sum(rate({__name__=~\"flyte:propeller:all:plugin:.*_failure_unlabeled\"}[5m]))",
     "legendFormat": "failure",
     "query": "sum(rate({__name__=~\"flyte:propeller:all:plugin:.*_failure_unlabeled\"}[5m]))"
    }
   ]
  },
  {
   "title": "Round Latency (includes streak rounds)",
   "type": "timeseries",
   "description": "Round latency breakdown. When there are streaks within one round each iteration is measured separately.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:round:raw_unlabeled_ms) by (quantile)",
     "legendFormat": "traverse-P{{quantile}}",
     "query": "sum(flyte:propeller:all:round:raw_unlabeled_ms) by (quantile)"
    },
    {
     "expr": "avg(flyte:propeller:all:round:raw_unlabeled_ms_sum/flyte:propeller:all:round:raw_unlabeled_ms_count)",
     "legendFormat": "traverse-mean",
     "query": "avg(flyte:propeller:all:round:raw_unlabeled_ms_sum/flyte:propeller:all:round:raw_unlabeled_ms_count)"
    },
    {
     "expr": "sum(flyte:propeller:all:round:round_time_ms) by (quantile)",
     "legendFormat": "total-P{{quantile}}",
     "query": "sum(flyte:propeller:all:round:round_time_ms) by (quantile)"
    },
    {
     "expr": "avg(flyte:propeller:all:round:round_time_unlabeled_ms_sum/flyte:propeller:all:round:round_time_unlabeled_ms_count)",
     "legendFormat": "total-mean",
     "query": "avg(flyte:propeller:all:round:round_time_unlabeled_ms_sum/flyte:propeller:all:round:round_time_unlabeled_ms_count)"
    }
   ]
  },
  {
   "title": "Round traverse latency per workflow",
   "type": "timeseries",
   "description": "Round latency by workflow name. When there are streaks within one round each iteration is measured separately.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:round:raw_ms) by (wf)",
     "legendFormat": "{{wf}}",
     "query": "sum(flyte:propeller:all:round:raw_ms) by (wf)"
    }
   ]
  },
  {
   "title": "Running Workflows per project",
   "type": "timeseries",
   "description": "Count of currently running workflows running per project",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:collector:flyteworkflow) by (project)",
     "query": "sum(flyte:propeller:all:collector:flyteworkflow) by (project)"
    }
   ]
  },
  {
   "title": "Workflow enqueue rate",
   "type": "timeseries",
   "description": "Rate at which workflows are being enqueued by flytepropeller. These enqueues all pass through the sub-queue before going back into the main queue.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(flyte:propeller:all:wf_enqueue[5m]))",
     "query": "sum by(type) (rate(flyte:propeller:all:wf_enqueue[5m]))"
    }
   ]
  },
  { "title": "FlytePropeller Queue metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Add rate to queue",
   "type": "timeseries",
   "description": "Rate at which items are actually added to the queue. If an item is already on the queue attempting to add it will be a no-op. Usually there is also rate limiting that will delay items from being added to the queue.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flyte:propeller:all:main_adds[5m]))",
     "legendFormat": "main",
     "query": "sum(rate(flyte:propeller:all:main_adds[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:sub_adds[5m]))",
     "legendFormat": "sub",
     "query": "sum(rate(flyte:propeller:all:sub_adds[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:admin_launcher:_adds[5m]))",
     "legendFormat": "admin_launcher",
     "query": "sum(rate(flyte:propeller:all:admin_launcher:_adds[5m]))"
    }
   ]
  },
  {
   "title": "Add rate before rate limiting and deduplication",
   "type": "timeseries",
   "description": "Tracks every rate limited add synchronously before rate limiting delays or deduplication",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flyte:propeller:all:main_retries[5m]))",
     "legendFormat": "main",
     "query": "sum(rate(flyte:propeller:all:main_retries[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:sub_retries[5m]))",
     "legendFormat": "sub",
     "query": "sum(rate(flyte:propeller:all:sub_retries[5m]))"
    },
    {
     "expr": "sum(rate(flyte:propeller:all:admin_launcher:_retries[5m]))",
     "legendFormat": "admin_launcher",
     "query": "sum(rate(flyte:propeller:all:admin_launcher:_retries[5m]))"
    }
   ]
  },
  {
   "title": "Unprocessed Queue depth",
   "type": "timeseries",
   "description": "The number of items that are currently in the queue but have not been processed yet.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:main_depth)",
     "legendFormat": "main",
     "query": "sum(flyte:propeller:all:main_depth)"
    },
    {
     "expr": "sum(flyte:propeller:all:sub_depth)",
     "legendFormat": "sub",
     "query": "sum(flyte:propeller:all:sub_depth)"
    },
    {
     "expr": "sum(flyte:propeller:all:admin_launcher:_depth)",
     "legendFormat": "admin_launcher",
     "query": "sum(flyte:propeller:all:admin_launcher:_depth)"
    }
   ]
  },
  {
   "title": "Seconds of unfinished work in progress",
   "type": "timeseries",
   "description": "Sum of the current in progress time of every in progress item in the queue.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(flyte:propeller:all:main_unfinished_work_s)",
     "legendFormat": "main",
     "query": "sum(flyte:propeller:all:main_unfinished_work_s)"
    },
    {
     "expr": "sum(flyte:propeller:all:sub_unfinished_work_s)",
     "legendFormat": "sub",
     "query": "sum(flyte:propeller:all:sub_unfinished_work_s)"
    },
    {
     "expr": "sum(flyte:propeller:all:admin_launcher:_unfinished_work_s)",
     "legendFormat": "admin_launcher",
     "query": "sum(flyte:propeller:all:admin_launcher:_unfinished_work_s)"
    }
   ]
  },
  {
   "title": "Metastore failures and cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache hit percentage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(flyte:propeller:all:metastore:cache_hit[5m])) * 100) / (sum(rate(flyte:propeller:all:metastore:cache_miss[5m])) + sum(rate(flyte:propeller:all:metastore:cache_hit[5m])))",
       "query": "(sum(rate(flyte:propeller:all:metastore:cache_hit[5m])) * 100) / (sum(rate(flyte:propeller:all:metastore:cache_miss[5m])) + sum(rate(flyte:propeller:all:metastore:cache_hit[5m])))"
      }
     ]
    },
    {
     "title": "Metastore failure rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:metastore:head_failure_unlabeled[5m]))",
       "legendFormat": "head-failure",
       "query": "sum(rate(flyte:propeller:all:metastore:head_failure_unlabeled[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:metastore:bad_container_unlabeled[5m]))",
       "legendFormat": "bad-container",
       "query": "sum(rate(flyte:propeller:all:metastore:bad_container_unlabeled[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:metastore:bad_key_unlabeled[5m]))",
       "legendFormat": "bad-key",
       "query": "sum(rate(flyte:propeller:all:metastore:bad_key_unlabeled[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:metastore:read_failure_unlabeled[5m]))",
       "legendFormat": "read-failure",
       "query": "sum(rate(flyte:propeller:all:metastore:read_failure_unlabeled[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:metastore:write_failure_unlabeled[5m]))",
       "legendFormat": "write-failure",
       "query": "sum(rate(flyte:propeller:all:metastore:write_failure_unlabeled[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Metastore latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metastore copy latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:metastore:copy:overall_unlabeled_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:metastore:copy:overall_unlabeled_ms) by (quantile)"
      }
     ]
    },
    {
     "title": "Metastore write latency by workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:metastore:write_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:metastore:write_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "Metastore read open latency by workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:metastore:read_open_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:metastore:read_open_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "Metastore head latency by workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:metastore:head_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:metastore:head_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "Metastore fetch latency by workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:metastore:proto_fetch_ms) by (quantile, wf)",
       "legendFormat": "proto-fetch-P{{quantile}}",
       "query": "sum(flyte:propeller:all:metastore:proto_fetch_ms) by (quantile, wf)"
      },
      {
       "expr": "sum(flyte:propeller:all:metastore:remote_fetch_ms) by (quantile, wf)",
       "legendFormat": "remote-fetch-P{{quantile}}",
       "query": "sum(flyte:propeller:all:metastore:remote_fetch_ms) by (quantile, wf)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exec latency quantile and workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:node_exec_latency_us) by (quantile, wf) / 1000",
       "query": "sum(flyte:propeller:all:node:node_exec_latency_us) by (quantile, wf) / 1000"
      }
     ]
    },
    {
     "title": "Node Input latency quantile and workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:node_input_latency_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:node:node_input_latency_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "Node Event event recording latency quantile and workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:event_recording:success_duration_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:node:event_recording:success_duration_ms) by (quantile, wf)"
      },
      {
       "expr": "sum(flyte:propeller:all:node:event_recording:failure_duration_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:node:event_recording:failure_duration_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "node event recording error rate breakdown",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:node:perma_system_error_duration_unlabeled_ms_count[5m]))",
       "legendFormat": "system error",
       "query": "sum(rate(flyte:propeller:all:node:perma_system_error_duration_unlabeled_ms_count[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:node:perma_user_error_duration_unlabeled_ms[5m]))",
       "legendFormat": "user error",
       "query": "sum(rate(flyte:propeller:all:node:perma_user_error_duration_unlabeled_ms[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:node:perma_unknown_error_duration_unlabeled_ms[5m]))",
       "legendFormat": "unknown error",
       "query": "sum(rate(flyte:propeller:all:node:perma_unknown_error_duration_unlabeled_ms[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Perf metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "wf event recording latency success",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:workflow:event_recording:success_duration_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:workflow:event_recording:success_duration_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "wf event recording rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:workflow:event_recording:success_duration_ms_count[5m])) by (wf)",
       "legendFormat": "success",
       "query": "sum(rate(flyte:propeller:all:workflow:event_recording:success_duration_ms_count[5m])) by (wf)"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:workflow:event_recording:failure_duration_ms_count[5m])) by (wf)",
       "legendFormat": "failure",
       "query": "sum(rate(flyte:propeller:all:workflow:event_recording:failure_duration_ms_count[5m])) by (wf)"
      }
     ]
    },
    {
     "title": "node event recording latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:event_recording:success_duration_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:node:event_recording:success_duration_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "node event recording rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:node:event_recording:success_duration_ms_count[5m])) by (wf)",
       "legendFormat": "success-{{wf}}",
       "query": "sum(rate(flyte:propeller:all:node:event_recording:success_duration_ms_count[5m])) by (wf)"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:node:event_recording:failure_duration_ms_count[5m])) by (wf)",
       "legendFormat": "failure-{{wf}}",
       "query": "sum(rate(flyte:propeller:all:node:event_recording:failure_duration_ms_count[5m])) by (wf)"
      }
     ]
    },
    {
     "title": "task event recording latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:task:event_recording:success_duration_ms) by (quantile, wf)",
       "query": "sum(flyte:propeller:all:task:event_recording:success_duration_ms) by (quantile, wf)"
      }
     ]
    },
    {
     "title": "task event recording rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:task:event_recording:success_duration_ms_count[5m])) by (wf)",
       "legendFormat": "success-{{wf}}",
       "query": "sum(rate(flyte:propeller:all:task:event_recording:success_duration_ms_count[5m])) by (wf)"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:task:event_recording:failure_duration_ms_count[5m])) by (wf)",
       "legendFormat": "failure-{{wf}}",
       "query": "sum(rate(flyte:propeller:all:task:event_recording:failure_duration_ms_count[5m])) by (wf)"
      }
     ]
    },
    {
     "title": "Dynamic workflow build latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:build_dynamic_workflow_us) by (quantile, wf) / 1000",
       "query": "sum(flyte:propeller:all:node:build_dynamic_workflow_us) by (quantile, wf) / 1000"
      }
     ]
    },
    {
     "title": "Dynamic workflow build rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:node:build_dynamic_workflow_us_count[5m])) by (wf)",
       "query": "sum(rate(flyte:propeller:all:node:build_dynamic_workflow_us_count[5m])) by (wf)"
      }
     ]
    },
    {
     "title": "Admin Launcher cache hit/miss rate",
     "type": "timeseries",
     "description": "Cache hit rate when admin launcher is queried for the status of a workflow. Admin launcher will update status of workflows in the cache on a polling interval.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:admin_launcher:cache_hit[5m]))",
       "legendFormat": "hit",
       "query": "sum(rate(flyte:propeller:all:admin_launcher:cache_hit[5m]))"
      },
      {
       "expr": "sum(rate(flyte:propeller:all:admin_launcher:cache_miss[5m]))",
       "legendFormat": "miss",
       "query": "sum(rate(flyte:propeller:all:admin_launcher:cache_miss[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC latency metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "All GRPC calls latency",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum by(le) (rate(grpc_client_handling_seconds_bucket[5m]))",
       "legendFormat": "{{le}}",
       "query": "sum by(le) (rate(grpc_client_handling_seconds_bucket[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow acceptance latency per workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:workflow:acceptance_latency_ms) by (wf)",
       "query": "sum(flyte:propeller:all:workflow:acceptance_latency_ms) by (wf)"
      }
     ]
    },
    {
     "title": "Workflow acceptance latency by quantile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:workflow:acceptance_latency_unlabeled_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:workflow:acceptance_latency_unlabeled_ms) by (quantile)"
      }
     ]
    },
    {
     "title": "Node transition latency per workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:transition_latency_ms) by (wf)",
       "query": "sum(flyte:propeller:all:node:transition_latency_ms) by (wf)"
      }
     ]
    },
    {
     "title": "Node transition latency by quantile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:transition_latency_unlabeled_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:node:transition_latency_unlabeled_ms) by (quantile)"
      }
     ]
    },
    {
     "title": "Node queueing latency per workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:queueing_latency_ms) by (wf)",
       "query": "sum(flyte:propeller:all:node:queueing_latency_ms) by (wf)"
      }
     ]
    },
    {
     "title": "Node queueing latency by quantile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:node:queueing_latency_unlabeled_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:node:queueing_latency_unlabeled_ms) by (quantile)"
      }
     ]
    },
    {
     "title": "Workflow completion latency per workflow",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:workflow:completion_latency_ms) by (wf)",
       "query": "sum(flyte:propeller:all:workflow:completion_latency_ms) by (wf)"
      }
     ]
    },
    {
     "title": "Workflow completion latency by quantile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:workflow:completion_latency_unlabeled_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:workflow:completion_latency_unlabeled_ms) by (quantile)"
      }
     ]
    }
   ]
  },
  {
   "title": "etcD write metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "wf update etcD latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:wf_update_latency_ms) by (quantile)",
       "query": "sum(flyte:propeller:all:wf_update_latency_ms) by (quantile)"
      }
     ]
    },
    {
     "title": "etcD write rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_update_latency_ms_count[5m]))",
       "query": "sum(rate(flyte:propeller:all:wf_update_latency_ms_count[5m]))"
      }
     ]
    },
    {
     "title": "etcD write conflict rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_update_conflict[5m]))",
       "query": "sum(rate(flyte:propeller:all:wf_update_conflict[5m]))"
      }
     ]
    },
    {
     "title": "etcD write failure rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_update_failed[5m]))",
       "query": "sum(rate(flyte:propeller:all:wf_update_failed[5m]))"
      }
     ]
    },
    {
     "title": "etcD write too large rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_too_large[5m]))",
       "query": "sum(rate(flyte:propeller:all:wf_too_large[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "K8s Pod Informer stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Update event rate from informer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:node:container:container:informer_update[5m]))",
       "query": "sum(rate(flyte:propeller:all:node:container:container:informer_update[5m]))"
      }
     ]
    },
    {
     "title": "Update events drop rate becacuse they have the same resource version",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:node:container:container:informer_update_dropped[5m]))",
       "query": "sum(rate(flyte:propeller:all:node:container:container:informer_update_dropped[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stale workflows rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_stale_unlabeled[5m])) by (quantile)",
       "query": "sum(rate(flyte:propeller:all:wf_stale_unlabeled[5m])) by (quantile)"
      }
     ]
    },
    {
     "title": "Evict workflows rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_stale_unlabeled[5m])) by (quantile)",
       "query": "sum(rate(flyte:propeller:all:wf_stale_unlabeled[5m])) by (quantile)"
      }
     ]
    },
    {
     "title": "Workflow redundant updates rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flyte:propeller:all:wf_redundant_unlabeled[5m])) by (quantile)",
       "query": "sum(rate(flyte:propeller:all:wf_redundant_unlabeled[5m])) by (quantile)"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace successful garbage collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:gc_success)",
       "query": "sum(flyte:propeller:all:gc_success)"
      }
     ]
    },
    {
     "title": "Namespace failed garbage collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:gc_failure)",
       "query": "sum(flyte:propeller:all:gc_failure)"
      }
     ]
    },
    {
     "title": "Total completed garbage collection rounds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:gc_latency_ms_count)",
       "query": "sum(flyte:propeller:all:gc_latency_ms_count)"
      }
     ]
    },
    {
     "title": "Average garbage collection round duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(flyte:propeller:all:gc_latency_ms_sum) / sum(flyte:propeller:all:gc_latency_ms_count)",
       "query": "sum(flyte:propeller:all:gc_latency_ms_sum) / sum(flyte:propeller:all:gc_latency_ms_count)"
      }
     ]
    }
   ]
  }
 ]
}