{
 "title": "Altinity ClickHouse Operator Dashboard",
 "description": "Alitinity Clickhouse Operator metrics exported by Monitoring Agent",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "chi",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\"}, chi)"
    }
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\",chi=~\"$chi\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(avg by (hostname)(chi_clickhouse_metric_Uptime{chi=~\"$chi\",hostname=~\"$hostname\"})) OR on () vector(0)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Clickhouse operator metrics-exporter fails when grab metrics from clickhouse-server\n\nPlease look pods status\n\nkubectl get pods --all-namespaces | grep clickhouse",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chi_clickhouse_metric_fetch_errors{chi=~\"$chi\",hostname=~\"$hostname\",fetch_type=\"system.metrics\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "description": "For example, version 11.22.33 is translated to 11022033",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sort_desc(max by (hostname) (chi_clickhouse_metric_VersionInteger{chi=~\"$chi\",hostname=~\"$hostname\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chi_clickhouse_metric_NumberOfTables{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "Tables"
    },
    {
     "expr": "max(chi_clickhouse_metric_NumberOfDatabases{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "Databases"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chi_clickhouse_metric_VersionInteger{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "Version"
    }
   ]
  },
  {
   "title": "ReadOnly replicas",
   "type": "stat",
   "description": "Check Zookeeper connection, Disk Free space and network interconnection between replicas ASAP",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chi_clickhouse_metric_ReadonlyReplica{chi=~\"$chi\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "DNS and Distributed Connection Errors",
   "type": "timeseries",
   "description": "Show DNS errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_NetworkErrors{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "NetworkErrors {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailAtAll{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "DistributedConnectionFailAtAll {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DistributedConnectionFailTry{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "DistributedConnectionFailTry {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DNSError{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "DNSErrors {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication and ZooKeeper Exceptions",
   "type": "timeseries",
   "description": "Show readonly and partial shutdown replicas, zookeeer exceptions, zookeeer sessions, zookeeper init requests",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReadonlyReplica{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "ReadonlyReplica {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ReplicaPartialShutdown{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "ReplicaPartialShutdown {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperInit{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "ZooKeeperInit {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_metric_ZooKeeperSession{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "ZooKeeperSession  {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperHardwareExceptions{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "ZooKeeperHardwareExceptions  {{hostname}}"
    }
   ]
  },
  {
   "title": "Delayed/Rejected/Pending Inserts",
   "type": "timeseries",
   "description": "delayed query\nNumber of INSERT queries that are throttled due to high number of active data parts for partition in a *MergeTree table.\n\ndelayed blocks\nNumber of times the INSERT of a block to a *MergeTree table was throttled due to high number of active data parts for partition. \n\nrejected blocks\nNumber of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition.\n\n\nplease look\nparts_to_delay_insert\nparts_to_throw_insert\n\nin system.merge_tree_settings table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DelayedInserts{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "delayed  queries {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DelayedInserts{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "delayed blocks {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RejectedInserts{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "rejected blocks {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_DistributedFilesToInsert{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "pending distributed files {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_BrokenDistributedFilesToInsert{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "broken distributed files {{ hostname }}"
    }
   ]
  },
  {
   "title": "Queries (running)",
   "type": "timeseries",
   "description": "Number of executing queries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (hostname) (max_over_time(chi_clickhouse_metric_Query{chi=~\"$chi\",hostname=~\"$hostname\"}[$__interval])-1) OR on () vector(0) > 0",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(chi_clickhouse_metric_Query{chi=~\"$chi\",hostname=~\"$hostname\"}-1) OR on () vector(0)",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Select Queries (started per sec)",
   "type": "timeseries",
   "description": "Number of executing select queries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(chi_clickhouse_event_SelectQuery{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])) OR on () vector(0)",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Memory for Queries",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated in currently executing queries. \n\nNote that some memory allocations may not be accounted.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryTracking{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Insert Queries (running)",
   "type": "timeseries",
   "description": "Number of running INSERT queries. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertQuery{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert queries {{hostname}}"
    }
   ]
  },
  {
   "title": "Insert Queries (started per sec)",
   "type": "timeseries",
   "description": "Number of executing insert queries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(chi_clickhouse_event_InsertQuery{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])) OR on () vector(0)",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Rows Inserted",
   "type": "timeseries",
   "description": "## Tracks rows of inserted data.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertedRows{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Replication Queue Jobs",
   "type": "timeseries",
   "description": "Show how intensive data exchange between replicas in parts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedDataLoss{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "data loss {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartChecks{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "check {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartChecksFailed{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "check fail {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFetches{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "fetch {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFailedFetches{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "fetch fail {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartFetchesOfMerged{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "fetch merged {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_ReplicatedPartMerges{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "replicated merge {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicasSumInsertsInQueue{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "inserts in queue {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicasSumMergesInQueue{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "merges in queue {{hostname}}"
    }
   ]
  },
  {
   "title": "Max Replica Delay",
   "type": "timeseries",
   "description": "Show seconds when replicated servers can be delayed relative to current time,  when you insert directly in *ReplicatedMegreTree table on one server clickhouse need time to replicate new parts of data to another servers in same shard in background",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxAbsoluteDelay{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "absolute {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxRelativeDelay{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "relative {{hostname}}"
    }
   ]
  },
  {
   "title": "Zookeeper Transactions",
   "type": "timeseries",
   "description": "Number of requests to ZooKeeper transactions per seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_ZooKeeperTransactions{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "transactions {{ hostname }}"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_Merge{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "merges {{hostname}}"
    }
   ]
  },
  {
   "title": "Merged Rows",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MergedRows{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "rows {{hostname}}"
    }
   ]
  },
  {
   "title": "Merged Uncompressed Bytes",
   "type": "timeseries",
   "description": "Show how intensive background merge processes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MergedUncompressedBytes{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "bytes {{hostname}}"
    }
   ]
  },
  {
   "title": "Active Parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname) (chi_clickhouse_table_parts{chi=~\"$chi\",hostname=~\"$hostname\",active=\"1\"})",
     "legendFormat": "Parts {{hostname}}"
    }
   ]
  },
  {
   "title": "Detached parts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname,reason) (chi_clickhouse_metric_DetachedParts{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "{{reason}} {{hostname}} "
    }
   ]
  },
  {
   "title": "Max Part count for Partition",
   "type": "timeseries",
   "description": "Each logical partition defined over `PARTITION BY` contains few physical data \"parts\" ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MaxPartCountForPartition{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": " clickhouse-server Process Memory",
   "type": "timeseries",
   "description": "Memory size allocated for clickhouse-server process\nAvailable for ClickHouse 20.4+\n\nVIRT \nThe total amount of virtual memory used by the task. It includes all code, data and shared libraries plus pages that have been swapped out.\n\nVIRT = SWAP + RES\n\n\nSWAP -- Swapped size (kb)\nThe swapped out portion of a task's total virtual memory image.\n\nRES -- Resident size (kb)\nThe non-swapped physical memory a task has used.\nRES = CODE + USED DATA.\n\nCODE -- Code size (kb)\nThe amount of physical memory devoted to executable code, also known as the 'text resident set' size or TRS\n\nDATA -- Data+Stack size (kb)\nThe amount of physical memory allocated to other than executable code, also known as the 'data resident set' size or DRS.\n\nSHR -- Shared Mem size (kb)\nThe amount of shared memory used by a task. It simply reflects memory that could be potentially shared with other processes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryCode{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "CODE {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryResident{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "RES {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryShared{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "SHR {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryDataAndStack{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "DATA {{ hostname }}"
    },
    {
     "expr": "chi_clickhouse_metric_MemoryVirtual{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "VIRT {{ hostname }}"
    }
   ]
  },
  {
   "title": "Primary Keys Memory",
   "type": "timeseries",
   "description": "Memory size allocated for primary keys",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryPrimaryKeyBytesAllocated{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Dictionary Memory",
   "type": "timeseries",
   "description": "Memory size allocated for dictionaries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_MemoryDictionaryBytesAllocated{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "timeseries",
   "description": "shows how much space available in the kubernetes pod\n\nbe careful with multiple volumes configuration, kubernetes volume claims and S3 as storage backend",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskFreeBytes{chi=~\"$chi\",hostname=~\"$hostname\"} / chi_clickhouse_metric_DiskTotalBytes{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ disk }} {{hostname}}"
    }
   ]
  },
  {
   "title": "Table Stats",
   "type": "table",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum by (database, table) (chi_clickhouse_table_parts_bytes{chi=~\"$chi\",hostname=~\"$hostname\", active=\"1\"})",
     "legendFormat": "Bytes"
    },
    {
     "expr": "sum by (database, table) (chi_clickhouse_table_parts_rows{chi=~\"$chi\",hostname=~\"$hostname\", active=\"1\"})",
     "legendFormat": "Rows"
    },
    {
     "expr": "sum by (database, table) (chi_clickhouse_table_parts{chi=~\"$chi\",hostname=~\"$hostname\", active=\"1\"})",
     "legendFormat": "Parts"
    }
   ]
  },
  {
   "title": "Clickhouse Data size on Disk",
   "type": "timeseries",
   "description": "Total data size for all ClickHouse *MergeTree tables\n\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskDataBytes{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Background Tasks",
   "type": "timeseries",
   "description": "BackgroundPoolTask\t\n---\nNumber of active tasks in BackgroundProcessingPool (merges, mutations, fetches, or replication queue bookkeeping)\n\n\nBackgroundMovePoolTask\n---\nNumber of active tasks in BackgroundProcessingPool for moves\n\n\nBackgroundSchedulePoolTask\t\n---\nA number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_BackgroundPoolTask{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "merge, mutate, fetch {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundSchedulePoolTask{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "clean, alter, replica re-init {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_BackgroundMovePoolTask{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "moves {{hostname}}"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "timeseries",
   "description": "Number of active mutations (ALTER DELETE/ALTER UPDATE) and parts to mutate",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (chi_clickhouse_table_mutations{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "mutations {{hostname}}"
    },
    {
     "expr": "sum by (hostname) (chi_clickhouse_table_mutations_parts_to_do{chi=~\"$chi\",hostname=~\"$hostname\"})",
     "legendFormat": "parts_to_do {{hostname}}"
    }
   ]
  },
  {
   "title": "Marks Cache Hit Rate",
   "type": "timeseries",
   "description": "Show which percent of mark files (.mrk) read from memory instead of disk",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_MarkCacheHits{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) / (irate(chi_clickhouse_event_MarkCacheHits{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) + irate(chi_clickhouse_event_MarkCacheMisses{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Time per second",
   "type": "timeseries",
   "description": "The time which CPU spent on various types of activity ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_RealTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Real Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_UserTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "User Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_SystemTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "System Time {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSIOWaitMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS IO Wait {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSCPUWaitMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS CPU Wait {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_OSCPUVirtualTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS CPU Virtual {{hostname}}"
    }
   ]
  },
  {
   "title": "Network / Disk CPU Time per second",
   "type": "timeseries",
   "description": "The time which CPU spent on various types of activity ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_DiskReadElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Disk Read syscall {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_DiskWriteElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Disk Write syscall {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_NetworkReceiveElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Network Receive {{hostname}}"
    },
    {
     "expr": "irate(chi_clickhouse_event_NetworkSendElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Network Send {{hostname}}"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_LoadAverage1{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Time total",
   "type": "piechart",
   "description": "The time which CPU spent on various types of activity total for the selected period",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "format": "µs",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_DiskReadElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Disk Read syscall {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DiskWriteElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Disk Write syscall {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_NetworkReceiveElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Network Receive {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_NetworkSendElapsedMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Network Send {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RealTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Real Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_UserTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "User Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_SystemTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "System Time {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSIOWaitMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS IO Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUWaitMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS CPU Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUVirtualTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "OS CPU Virtual {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ThrottlerSleepMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Throttler Sleep {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_DelayedInsertsMilliseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) * 1000",
     "legendFormat": "Delayed Insert {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperWaitMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Zookeeper Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_CompileExpressionsMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Compile Expressions {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_MergesTimeMilliseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) * 1000",
     "legendFormat": "Merges {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockReadersWaitMilliseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) * 1000",
     "legendFormat": "RWLock Reader Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockWritersWaitMilliseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m]) * 1000",
     "legendFormat": "RWLock Writer Wait {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_SelectQueryTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Select Query {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_InsertQueryTimeMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "Insert Query {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3ReadMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "S3 Read {{hostname}}"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3WriteMicroseconds{chi=~\"$chi\",hostname=~\"$hostname\"}[1m])",
     "legendFormat": "S3 Write {{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_TCPConnection{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "tcp {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_HTTPConnection{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "http {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_InterserverConnection{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "interserver {{hostname}}"
    },
    {
     "expr": "chi_clickhouse_metric_MySQLConnection{chi=~\"$chi\",hostname=~\"$hostname\"}",
     "legendFormat": "mysql {{hostname}}"
    }
   ]
  }
 ]
}