{
 "title": "Batch",
 "description": "Visualize AWS Batch metrics",
 "tags": [
  "AWS",
  "Exporter",
  "Batch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values(aws_batch_succeeded_job,queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Jobs Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runnable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_batch_runnable_job)" }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_batch_running_job)" }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_batch_succeeded_job)" }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aws_batch_failed_job)" }
   ]
  },
  {
   "title": "Runnable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sum(aws_batch_runnable_job)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "sum(aws_batch_running_job)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "sum(aws_batch_succeeded_job)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "targets": [
    { "expr": "sum(aws_batch_failed_job)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Runnable (per definition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (definition) (aws_batch_runnable_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running (per definition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum by (definition) (aws_batch_running_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded (per definition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (definition) (aws_batch_succeeded_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed (per definition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by (definition) (aws_batch_failed_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Queue Overview: \"$queue\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "queue"
  },
  {
   "title": "Priority",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Submitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_submitted_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_pending_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Runnable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_runnable_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Starting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_starting_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_running_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_succeeded_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aws_batch_failed_job{queue=\"$queue\"}) by (queue)"
    }
   ]
  },
  { "title": "Job Queue History (Detailed)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Submitted Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(aws_batch_submitted_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(aws_batch_pending_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Runnable Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(aws_batch_runnable_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Starting Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(aws_batch_starting_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(aws_batch_running_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(aws_batch_succeeded_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(aws_batch_failed_job) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}