{
 "title": "EFS",
 "description": "Visualize AWS EFS metrics",
 "tags": [
  "AWS",
  "Cloudwatch",
  "EFS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "fs_id",
    "label": "FileSystemID",
    "query": {
     "query": "label_values(aws_efs_storage_bytes_maximum,file_system_id)"
    }
   },
   { "name": "delta", "label": "delta", "query": "None : 0s, 1h, 1d, 7d, 30d" }
  ]
 },
 "panels": [
  {
   "title": "Storage Bytes (max)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "sum by (file_system_id) (aws_efs_storage_bytes_maximum{file_system_id=~\"$fs_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{file_system_id}}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total IO Bytes (avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "sum by (file_system_id) (aws_efs_total_iobytes_average{file_system_id=~\"$fs_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{file_system_id}}",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "expr": "(delta(aws_efs_total_iobytes_average[$delta]) and on() $delta != 0s) or absent(vector(1))",
     "legendFormat": "delta[$delta]: {{file_system_id}}"
    }
   ]
  },
  {
   "title": "Burst Credit Balance (min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "sum by (file_system_id) (aws_efs_burst_credit_balance_minimum{file_system_id=~\"$fs_id\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{file_system_id}}",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/EFS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "expr": "(delta(aws_efs_burst_credit_balance_minimum[$delta]) and on() $delta != 0s) or absent(vector(1))",
     "legendFormat": "delta[$delta]: {{file_system_id}}"
    }
   ]
  }
 ]
}