{
 "title": "Aurora RDS",
 "description": "Visualize AWS RDS metrics",
 "tags": [
  "Aurora",
  "AWS",
  "CloudWatch",
  "RDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": {
     "query": "label_values(aws_rds_cpuutilization_average{exported_job=\"aws_rds\"}, dbinstance_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"$dbinstanceidentifier\"} ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dbinstance_identifier}}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections (max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_rds_database_connections_maximum{dbinstance_identifier=~\"$dbinstanceidentifier\"}  ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dbinstance_identifier}}",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Freeable Memory (min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_rds_freeable_memory_minimum{dbinstance_identifier=~\"$dbinstanceidentifier\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dbinstance_identifier}}",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Local Storage (min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_rds_free_local_storage_minimum{dbinstance_identifier=~\"$dbinstanceidentifier\"}",
     "expression": "aws_rds_database_connections_maximum{dbinstance_identifier=~\"$dbinstanceidentifier\"}  ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dbinstance_identifier}}",
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_rds_cpucredit_balance_average{dbinstance_identifier=~\"$dbinstanceidentifier\"}",
     "expression": "aws_rds_database_connections_maximum{dbinstance_identifier=~\"$dbinstanceidentifier\"}  ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{dbinstance_identifier}}",
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}