{
 "title": "OpenSearch",
 "description": "Visualize AWS OpenSearch metrics",
 "tags": [
  "AWS",
  "CloudWatch",
  "OpenSearch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "domain_name",
    "label": "DomainName",
    "query": {
     "query": "label_values(aws_es_cluster_status_green_minimum,domain_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_minimum{domain_name=~\"$domain_name\"} * 1 + aws_es_cluster_status_yellow_minimum{domain_name=~\"$domain_name\"} * 0 + aws_es_cluster_status_red_minimum{domain_name=~\"$domain_name\"} * -1",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Cluster Index Writes Blocked",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_index_writes_blocked_minimum{domain_name=~\"$domain_name\"}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_es_cpuutilization_maximum{domain_name=~\"$domain_name\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{domain_name}}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_es_sys_memory_utilization_maximum{domain_name=~\"$domain_name\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{domain_name}}",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_es_free_storage_space_minimum{domain_name=~\"$domain_name\"}",
     "expression": "aws_rds_database_connections_maximum{dbinstance_identifier=~\"$dbinstanceidentifier\"}  ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{domain_name}}",
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "expr": "aws_es_deleted_documents_minimum{domain_name=~\"$domain_name\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{domain_name}}",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}