{
 "title": "SNS",
 "description": "Visualize AWS SNS metrics",
 "tags": [
  "AWS",
  "CloudWatch",
  "SNS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(aws_sns_number_of_notifications_delivered_sum{exported_job=\"aws_sns\"},topic_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delivered Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum by(topic_name) (rate(aws_sns_number_of_notifications_delivered_sum{topic_name=~\"$topic\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{queue_name}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Failed Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum by(topic_name) (rate(aws_sns_number_of_notifications_failed_sum{topic_name=~\"$topic\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{queue_name}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Published Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum by(topic_name) (rate(aws_sns_number_of_messages_published_sum{topic_name=~\"$topic\"}[$__rate_interval]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{queue_name}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Published Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "sum by(topic_name) (aws_sns_publish_size_average{topic_name=~\"$topic\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{queue_name}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}