{
 "title": "Kafka MSK",
 "description": "Visualize AWS Kafka (MSK) metrics",
 "tags": [
  "AWS",
  "Multiplayer",
  "Cloudwatch",
  "Kafka",
  "msk"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "kafka_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aws_kafka_bytes_in_per_sec_average{exported_job=\"aws_kafka\"},cluster)"
    }
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": {
     "query": "label_values(aws_kafka_bytes_in_per_sec_average{exported_job=\"aws_kafka\"},broker_id)"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "label_values(aws_kafka_bytes_in_per_sec_average{exported_job=\"aws_kafka\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "sum offset lag for all partitions in a topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_kafka_sum_offset_lag_average{cluster=~\"$kafka_cluster\",topic=~\"$kafka_topic\"}",
     "legendFormat": "Consumer group: {{consumer_group}}"
    }
   ]
  },
  {
   "title": "Disk usage by broker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_kafka_kafka_data_logs_disk_used_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  },
  {
   "title": "CPU credit balance by broker",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "aws_kafka_cpucredit_balance_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  },
  {
   "title": "CPU (System) usage by broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_kafka_cpu_system_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  },
  {
   "title": "CPU (User) usage by broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_kafka_cpu_user_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  },
  {
   "title": "Network RX packets by broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "aws_kafka_network_rx_packets_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  },
  {
   "title": "Network TX packets by broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "aws_kafka_network_tx_packets_average{broker_id=~\"$kafka_broker\"}",
     "legendFormat": "Broker: {{broker_id}}"
    }
   ]
  }
 ]
}