{
 "title": "Elasticache",
 "description": "Visualize AWS Elasticache metrics",
 "tags": [
  "AWS",
  "Cloudwatch",
  "Elasticache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cacheclusterid",
    "label": "CacheClusterId",
    "query": {
     "query": "label_values(aws_elasticache_cpuutilization_average{exported_job=\"aws_elasticache\"},cache_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average{cache_cluster_id=~\"$cacheclusterid\"} ",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Freeable Memory (min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_elasticache_freeable_memory_minimum{cache_cluster_id=~\"$cacheclusterid\"}",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  },
  {
   "title": "Database Connections (max)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "aws_elasticache_curr_connections_maximum{cache_cluster_id=~\"$cacheclusterid\"}",
     "legendFormat": "{{cache_cluster_id}}"
    }
   ]
  }
 ]
}